---
title: "R Notebook"
author: "Anika Liu (al862@cam.ac.uk)"
output:
  html_document:
    df_print: paged
---
Load libraries.
```{r}
library(pheatmap)
library(tidyverse)
library(ggrepel)
library(ggExtra)
library(RColorBrewer)
library(matrixStats)
library(clusterProfiler)
library(biomaRt)
library(msigdbr)
```
Load data.
```{r}
df<-read.csv('../../Data_Processing/Structure_Standardization_And_Clustering/data/standardized_compounds_excl_ambiguous.csv')
df_featimp<-read.csv('../data/Model_Results_Parameters/PT/feature_importances_PT.csv')
df_targetswinfo<-read.delim('../../Data_Processing/Target_Prediction/data/training_set_predicted_targets.txt')
colnames(df_targetswinfo)<-str_extract(colnames(df_targetswinfo), pattern = '\\w+$')

# ensembl = useMart("ensembl",dataset="hsapiens_gene_ensembl")
# annotation <- getBM(attributes=c("uniprotswissprot","hgnc_symbol", 'entrezgene_id'),
#                     filters="uniprotswissprot",
#                     values=df_targetswinfo$Uniprot, 
#                     mart=ensembl)
# colnames(annotation)<-c('Uniprot','Symbol','entrez')
# write.csv(annotation, '../data/enrichment/annotation_gene.csv')
annotation=read.csv('../data/enrichment/annotation_gene.csv', row.names = 1)
df_target<-df_targetswinfo[,-(1:16)]
df_target[(df_target==NaN)]<-NA
rownames(df_target)<-df_targetswinfo$Uniprot
df_targetinfo<-df_targetswinfo[,(1:16)]
```
Load functions.
```{r}
#Function to run wilcoxon 
runwilcoxon<-function(df_DILI, df_NoDILI, alternative="greater"){
    result<-as.data.frame(matrix(NA, nrow = ncol(df_DILI), ncol=2))
    colnames(result)<-c("statistic","p.value")
    rownames(result)<-colnames(df_DILI)
    for (index in 1:ncol(df_DILI)){
      feature=colnames(df_DILI)[index]
      contrast<-wilcox.test(x=df_DILI[,index],y=df_NoDILI[,index], alternative=alternative)
      result$statistic[index]=contrast$statistic
      result$p.value[index]=contrast$p.value
      
    }
    result$p.adj<-p.adjust(result$p.value, method="fdr")
    return(result)
  }

#Wrapper for running wilcoxon
rundiliwilcoxon<-function(DILIclass=c('vMost-DILI-Concern'), NoDILIclass=c('vNo-DILI-Concern')){
#Select DILI/NoDILI compounds
  NoDILI<-df%>%filter(vDILIConcern %in% NoDILIclass)
  df_NoDILI_pre<-as.data.frame(t(df_target[,which(colnames(df_target) %in% NoDILI$PubChem_CID)]))
  DILI<-df%>%filter(vDILIConcern %in% DILIclass)
  df_DILI_pre<-as.data.frame(t(df_target[,which(colnames(df_target) %in% DILI$PubChem_CID)]))
  
  #Filter out those with no variance in probability in both classes
  accept<-((apply(df_NoDILI_pre, 2, function(x) var(x, na.rm = T))>0)&
             (apply(df_DILI_pre, 2, function(x) var(x, na.rm = T))>0))
  
  df_NoDILI<-df_NoDILI_pre[,which(accept==TRUE)]
  df_DILI<-df_DILI_pre[,which(accept==TRUE)]
  
  #Run Wilcoxon
  result<-runwilcoxon(df_DILI = df_DILI, df_NoDILI = df_NoDILI, alternative = "greater")
  return(result)
}
```
Run DILI enrichment test.
```{r}
mcnc<-rundiliwilcoxon(DILIclass=c('vMost-DILI-Concern'), NoDILIclass=c('vNo-DILI-Concern'))
mclcnc<-rundiliwilcoxon(DILIclass=c('vLess-DILI-Concern','vMost-DILI-Concern'), NoDILIclass=c('vNo-DILI-Concern'))
all<-rundiliwilcoxon(DILIclass=c('vLess-DILI-Concern','vMost-DILI-Concern'), NoDILIclass=c('vNo-DILI-Concern', 'sider_inactive'))

allfeat<-data.frame('Uniprot'=rownames(mcnc),
                    'mcnc'=mcnc$p.adj,
                    'mclcnc'=mclcnc$p.adj,
                    'all'=all$p.adj)%>%
  left_join(annotation)

```
Generate RF vs. SVM feature importance figure.
```{r}
df_plotting<-allfeat%>%left_join(df_featimp)
df_plotting$label<-df_plotting$Symbol
df_plotting$label[which(df_plotting$RF_mcnc<0.0025&abs(df_plotting$SVM_mcnc)<0.4)]<-NA
df_plotting$label[which(df_plotting$mcnc>0.05)]<-NA
df_plotting$`Enrichment in DILI compounds`<-ifelse(df_plotting$mcnc<0.05,'Significant', 'Insignificant')
df_plotting<-df_plotting[order(df_plotting$mcnc),]
df_plotting$Uniprot<-factor(df_plotting$Uniprot, levels=rev(unique(df_plotting$Uniprot)))

df_sig=df_plotting%>%filter(mcnc<0.05)

p <- ggplot(df_plotting, aes(RF_mcnc, (SVM_mcnc), label=label)) +
  geom_point(data=subset(df_plotting,mcnc>0.05),alpha=0.5, color='#008EA0FF' )+ 
  geom_point(data=subset(df_plotting,mcnc<0.05), alpha=0.5, color='#FF6F00FF' )+ 
  theme_bw()+
  geom_label_repel(size=2.5, label.size = 0, label.padding = 0.1, min.segment.length = 0.1)+
  xlab('RF feature importance')+
  ylab('SVM feature importance')

g<-ggExtra::ggMarginal(p, type = "histogram", bins=100)

ggsave(filename = '../plots/featureimportance_RF_vs_SVM.pdf', g, width = 4.5, height=4.5)
```
Run enrichment analysis.
```{r}
    
hallmark = msigdbr(species = "Homo sapiens",category = 'H')
canonical_reactome = msigdbr(species = "Homo sapiens",category = 'C2', subcategory = 'CP:REACTOME')
canonical_wikipathways = msigdbr(species = "Homo sapiens",category = 'C2', subcategory = 'CP:WIKIPATHWAYS')
canonical_kegg = msigdbr(species = "Homo sapiens",category = 'C2', subcategory = 'CP:KEGG')
msigdbr_df<-bind_rows(canonical_kegg, canonical_reactome)%>%bind_rows(canonical_wikipathways)
msigdbr_t2g = msigdbr_df %>% dplyr::select(gs_name, entrez_gene) %>% as.data.frame()
canonical_wikipathways_t2g = canonical_wikipathways %>% dplyr::select(gs_name, entrez_gene) %>% as.data.frame()
canonical_reactome_t2g = canonical_reactome %>% dplyr::select(gs_name, entrez_gene) %>% as.data.frame()

for(index in 2:ncol(df_featimp)){
    df_enrichment<-data.frame()
    name<-colnames(df_featimp)[index]

screenlist=quantile(df_sig[,which(colnames(df_sig)==name)], probs=seq(0.9,1, 0.005))
  for (prob in seq(0.905,1, 0.005)) {
      t=quantile(df_sig[,which(colnames(df_sig)==name)], probs=prob)
      if(str_detect(name, pattern='SVM')){
            gene_oi=df_sig$Uniprot[which((df_sig[,which(colnames(df_plotting)==name)])>t)] 
      }
      if(str_detect(name, pattern='RF')){
            gene_oi=df_sig$Uniprot[which((df_sig[,which(colnames(df_sig)==name)])>t)] 
      }
    if(length(gene_oi)>0){
      
      x <- enricher(gene=as.character(unique(df_sig$entrez[
        which(df_sig$Uniprot %in% gene_oi)])), 
                    TERM2GENE = msigdbr_t2g,
                    pvalueCutoff=0.05,
        pAdjustMethod = 'BH',
        universe = as.character(unique(df_plotting$entrez)),
        minGSSize = 10)
     result<-x@result%>%dplyr::select(ID, p.adjust,Description)
     colnames(result)[which(colnames(result)=='p.adjust')]<-prob
     if (ncol(df_enrichment)==0){
       df_enrichment<-result
       }else{
         df_enrichment<-full_join(df_enrichment, result)
         }
    }
   
}
  write.csv(df_enrichment, paste0('../data/enrichment/',name,'.csv'), row.names = F)
}
```


Generate SI figures on enrichment over diferent thresholds.
```{r}
#RF_mcnc
#for (index in 2:7){
  name='RF_mcnc'
#  name<-colnames(df_featimp)[index]
  df_enrichment<-read.csv(paste0('../data/enrichment/',name,'.csv'), check.names = F)
  t<-setdiff(colnames(df_enrichment),c('ID', 'Description'))

  significant<-df_enrichment%>%filter(rowMins(as.matrix(df_enrichment%>%dplyr::select(-ID, -Description)), na.rm=T)<0.05)
  
    p_sig<-significant%>%column_to_rownames('Description')%>%dplyr::select(-ID)
    p_sig<-p_sig[,which(colMins(as.matrix(p_sig), na.rm=T)<0.05)] #A lot of columns without any significant result!
   p_sig<-p_sig[which(rowMins(as.matrix(p_sig), na.rm=T)<0.05),] #A
  pheatmap<-pheatmap((-log10(p_sig)), border_color='white',
         cluster_cols=F,
         show_rownames=T,
         na_col='white',
         fontsize=13,
        color =  c('grey',(colorRampPalette((brewer.pal(n = 7, name =
  "YlOrRd")))(100))), 
     breaks = c(0,seq(-log10(0.05),-log10(min(p_sig, na.rm=T)),by=((-log10(min(p_sig, na.rm = T))+log10(0.05))/100))))
  ggsave(pheatmap, filename=paste0('../plots/enrichment_',name,'.pdf'), height = 10, width = 15)
}

  name='SVM_mcnc'
#  name<-colnames(df_featimp)[index]
  df_enrichment<-read.csv(paste0('../data/enrichment/',name,'.csv'), check.names = F)
  t<-setdiff(colnames(df_enrichment),c('ID', 'Description'))

  significant<-df_enrichment%>%filter(rowMins(as.matrix(df_enrichment%>%dplyr::select(-ID, -Description)), na.rm=T)<0.05)
  
    p_sig<-significant%>%column_to_rownames('Description')%>%dplyr::select(-ID)
    p_sig<-p_sig[,which(colMins(as.matrix(p_sig), na.rm=T)<0.05)] #A lot of columns without any significant result!
   p_sig<-p_sig[which(rowMins(as.matrix(p_sig), na.rm=T)<0.05),] #A
  pheatmap<-pheatmap((-log10(p_sig)), border_color='white',
         cluster_cols=F,
         show_rownames=T,
         na_col='white',
         fontsize=13,
        color =  c('grey',(colorRampPalette((brewer.pal(n = 7, name =
  "YlOrRd")))(100))), 
     breaks = c(0,seq(-log10(0.05),-log10(min(p_sig, na.rm=T)),by=((-log10(min(p_sig, na.rm = T))+log10(0.05))/100))))
  ggsave(pheatmap, filename=paste0('../plots/enrichment_',name,'.pdf'), height = 20, width = 15)
  }
```
Prepare for cytoscape
```{r}
t=quantile(df_sig[,which(colnames(df_sig)=='RF_mcnc')], probs=0.97)
gene_oi=df_sig$Uniprot[which((df_sig[,which(colnames(df_plotting)=='RF_mcnc')])>t)] 
x_RF <- enricher(gene=as.character(unique(df_sig$entrez[
        which(df_sig$Uniprot %in% gene_oi)])), 
                    TERM2GENE = msigdbr_t2g,
                    pvalueCutoff=0.05,
        pAdjustMethod = 'BH',
        universe = as.character(unique(df_plotting$entrez)),
        minGSSize = 10)
t=quantile(df_sig[,which(colnames(df_sig)=='SVM_mcnc')], probs=0.97)
gene_oi=df_plotting$Uniprot[which((df_sig[,which(colnames(df_sig)=='SVM_mcnc')])>t)] 
x_SVM <- enricher(gene=as.character(unique(df_sig$entrez[which(df_sig$Uniprot %in% gene_oi)])),
                       pvalueCutoff=0.05,
                       pAdjustMethod = 'BH', 
                      TERM2GENE = msigdbr_t2g,
                       universe = as.character(unique(df_plotting$entrez)),
                       minGSSize = 10)


#Prepare for SI table
r_RF<-x_RF@result%>%
  filter(p.adjust<0.05)%>%
  dplyr::select(ID,Description,GeneRatio,BgRatio, p.adjust,geneID)

r_SVM<-x_SVM@result%>%
  filter(p.adjust<0.05)%>%
  dplyr::select(ID,Description,GeneRatio,BgRatio, p.adjust,geneID)

r3<-full_join(r_RF%>%
                mutate('RF_padj'=p.adjust)%>%
                mutate('RF_GeneRatio'=GeneRatio)%>%
                dplyr::select(-GeneRatio, -BgRatio, -p.adjust, -geneID),
              r_SVM%>%
                mutate('SVM_padj'=p.adjust)%>%
                mutate('SVM_GeneRatio'=GeneRatio)%>%
                dplyr::select(-GeneRatio, -BgRatio, -p.adjust, -geneID))%>%
  separate(ID, into = c('Database', 'Pathway'), sep = '_',extra = 'merge')%>%
  mutate(Pathway=gsub(Pathway, pattern = '_', replacement = ' '))%>%
  mutate(Pathway=ifelse(str_detect(Pathway, 'P450'), 'CYTOCHROME P450',ifelse(str_detect(Pathway, 'PHASE|OXIDATION'), 'BIOTRANSFORMATION', Pathway )))%>%
  arrange(Pathway)
write.csv(r3, '../data/enrichment/SI_table_pathways.csv', quote = F)
#Prepare for cytoscape figure
results_nodes<-rbind(r_RF%>%mutate(method='RF'),r_SVM%>%mutate(method='SVM'))%>%
  separate_rows(geneID, sep='/')%>%
  mutate('entrez'=as.numeric(geneID))%>%
  left_join(annotation)%>%
  separate(ID, into = c('Database', 'Pathway'), sep = '_',extra = 'merge')%>%
  mutate(Pathway=gsub(Pathway, pattern = '_', replacement = ' '))%>%
  mutate(Pathway=ifelse(str_detect(Pathway, 'P450'), 'CYTOCHROME P450',ifelse(str_detect(Pathway, 'PHASE|OXIDATION'), 'BIOTRANSFORMATION', Pathway )))%>%
  arrange(Pathway)
write.csv(results_nodes, '../data/enrichment/topinteractions_cytoscape_wikipathways_reactome.csv', quote = F)

#Prepare node information for cytoscape
nodes_pathways<-data.frame('nodes'=unique(results_nodes$Pathway))
nodes_pathways$pathway_annot<-ifelse((nodes_pathways$nodes %in% results_nodes$Pathway[which(results_nodes$method=='RF')]&nodes_pathways$nodes %in% results_nodes$Pathway[which(results_nodes$method=='SVM')]), 'SVM|RF',ifelse(nodes_pathways$nodes %in% results_nodes$Pathway[which(results_nodes$method=='SVM')], 'SVM', 'RF'))

nodes_genes<-results_nodes%>%dplyr::select(Symbol, entrez)%>%
  mutate('gene_RF'=ifelse(Symbol %in% results_nodes$Symbol[which(results_nodes$method=='RF')], T,F),
         'gene_SVM'=ifelse(Symbol %in% results_nodes$Symbol[which(results_nodes$method=='SVM')], T,F),
         'nodes'=Symbol)%>%
  mutate(gene_annot=ifelse(gene_RF&gene_SVM, 'SVM|RF', ifelse(gene_SVM, 'SVM', 'RF')))%>%
  dplyr::select(nodes, gene_annot)

nodes<-full_join(nodes_genes,nodes_pathways)
write.csv(nodes, '../data/enrichment/topnodes_cytoscape.csv', quote = F)


SI_table<-allfeat%>%filter(Uniprot %in%df_sig$Uniprot)%>%inner_join(df_featimp)%>%left_join(df_targetinfo)%>%
  filter(RF_mcnc>quantile(df_sig[,which(colnames(df_sig)=='RF_mcnc')], probs=0.97)|
           SVM_mcnc>quantile(df_sig[,which(colnames(df_sig)=='SVM_mcnc')],probs=0.97))%>%
  mutate(RF_top=ifelse(RF_mcnc>quantile(df_sig[,which(colnames(df_sig)=='RF_mcnc')], probs=0.97),1,0),
         SVM_top=ifelse(SVM_mcnc>quantile(df_sig[,which(colnames(df_sig)=='SVM_mcnc')], probs=0.97),1,0))%>%
  filter(mcnc<0.05)%>%dplyr::select(Symbol,Name, Protein_Classification, RF_mcnc, SVM_mcnc,RF_top,SVM_top)
write.csv(SI_table, '../data/enrichment/SI_table_genes.csv', quote = F, row.names = F)
```





